spring:
  application:
    name: job-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqlDB:3306/testing
    username: root
    password: root


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create

    
server:
  port: 8050
  
  servlet:
    context-path: /job-service/api
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/    