spring:
  application:
    name: company-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/testing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 654321
    
  jpa:
    hibernate:
      ddl-auto: create
      
server:
  port: 8060
      
  servlet:
    context-path: /company-service/api
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/