spring:
  application:
    name: company-service
    
  datasource:
    url: jdbc:postgresql://postgresDBserv:5432/testing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 654321
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      
server:
  port: 8060
      
  servlet:
    context-path: /company-service/api
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/